// ace-server.cpp: HTTP server for ACE-Step music generation
//
// Single binary, one port. All compute endpoints (POST /lm, POST /synth,
// POST /understand) are asynchronous: they validate the request, create a
// job, push it to a FIFO queue, and return the job ID immediately.
// A single worker thread processes jobs in order.
// Clients poll GET /job?id=N for status and fetch results with
// GET /job?id=N&result=1. POST /job?id=N&cancel=1 cancels a job.
//
// Job IDs are random 64-bit hex strings (non-predictable).
// Completed jobs are evicted FIFO when the pool exceeds MAX_JOBS.
// Running jobs are never evicted.
//
// Models are discovered by scanning --models directory at startup
// (reads GGUF metadata only, no weights loaded).
// Each request loads the model, executes, and frees it. No model persists
// in VRAM between requests unless --keep-loaded is set. GPU access is
// serialized by the single worker thread (no mutex needed).
//
// Available models are classified by their GGUF general.architecture:
//   acestep-lm       -> lm bucket
//   acestep-dit      -> dit bucket
//   acestep-text-enc -> text-enc bucket (singleton, first entry used)
//   acestep-vae      -> vae bucket      (singleton, first entry used)
//
// Endpoint requirements:
//   /lm         LM
//   /synth      DiT + Text-Enc + VAE
//   /understand LM + DiT + VAE

#include "audio-io.h"
#include "model-registry.h"
#include "pipeline-lm.h"
#include "pipeline-synth.h"
#include "pipeline-understand.h"
#include "request.h"
#include "synth-batch-runner.h"
#include "task-types.h"
#include "version.h"
#include "yyjson.h"

// embedded webui (generated by xxd.cmake from tools/webui/public/index.html.gz)
#include "index.html.gz.hpp"

// suppress warnings in third-party headers
#ifdef __GNUC__
#    pragma GCC diagnostic push
#    pragma GCC diagnostic ignored "-Wshadow"
#endif
#include "httplib.h"
#ifdef __GNUC__
#    pragma GCC diagnostic pop
#endif

#include <atomic>
#include <condition_variable>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <functional>
#include <memory>
#include <mutex>
#include <random>
#include <string>
#include <thread>
#include <unordered_map>
#include <vector>

#ifdef GGML_USE_CUDA
#    include <cuda_runtime_api.h>
#endif

#ifdef _WIN32
#    include <fcntl.h>
#    include <io.h>
#    ifndef STDERR_FILENO
#        define STDERR_FILENO 2
#    endif
#else
#    include <unistd.h>
#endif

// portable fd wrappers. avoids macros that collide with C++ method names
// (e.g. sink.write() in httplib would be eaten by a write() macro).
#ifdef _WIN32
static int fd_pipe(int fd[2]) {
    return _pipe(fd, 4096, _O_BINARY);
}

static int fd_dup(int fd) {
    return _dup(fd);
}

static int fd_dup2(int src, int dst) {
    return _dup2(src, dst);
}

static int fd_read(int fd, void * buf, size_t n) {
    return _read(fd, buf, (unsigned) n);
}

static int fd_write(int fd, const void * buf, size_t n) {
    return _write(fd, buf, (unsigned) n);
}

static void fd_close(int fd) {
    _close(fd);
}
#else
static int fd_pipe(int fd[2]) {
    return pipe(fd);
}

static int fd_dup(int fd) {
    return dup(fd);
}

static int fd_dup2(int src, int dst) {
    return dup2(src, dst);
}

static int fd_read(int fd, void * buf, size_t n) {
    return (int) read(fd, buf, n);
}

static int fd_write(int fd, const void * buf, size_t n) {
    return (int) write(fd, buf, n);
}

static void fd_close(int fd) {
    close(fd);
}
#endif

// server instance pointer for the signal handler
static httplib::Server * g_svr = nullptr;

static void on_signal(int) {
    if (g_svr) {
        g_svr->stop();
    }
}

// work queue: all GPU jobs go through a single FIFO queue processed
// by one worker thread. GPU access is serialized by construction.
static std::deque<std::function<void()>> g_work_queue;
static std::mutex                        mtx_work;
static std::condition_variable           cv_work;
static bool                              g_work_stop = false;

static void work_push(std::function<void()> fn) {
    std::lock_guard<std::mutex> lock(mtx_work);
    g_work_queue.push_back(std::move(fn));
    cv_work.notify_one();
}

// worker thread: consume jobs in FIFO order until shutdown.
// on stop: finishes the current job, discards pending ones.
static void worker_main() {
    for (;;) {
        std::function<void()> fn;
        {
            std::unique_lock<std::mutex> lock(mtx_work);
            cv_work.wait(lock, [] { return g_work_stop || !g_work_queue.empty(); });
            if (g_work_stop) {
                break;
            }
            fn = std::move(g_work_queue.front());
            g_work_queue.pop_front();
        }
        fn();
    }
}

// pipeline contexts. NULL when not loaded.
static AceLm *         g_ctx_lm         = nullptr;
static AceSynth *      g_ctx_synth      = nullptr;
static AceUnderstand * g_ctx_understand = nullptr;

// model registry (populated at startup from GGUF metadata)
static ModelRegistry g_registry;

// loaded model names (empty = nothing loaded)
static std::string g_loaded_lm;
static std::string g_loaded_dit;
static std::string g_loaded_adapter;
static float       g_loaded_adapter_scale = 1.0f;
static AdapterGroupScales g_loaded_adapter_gs;
static std::string g_loaded_adapter_mode;
static std::string g_loaded_und_dit;
static std::string g_loaded_vae;

// pipeline params (rebuilt from registry paths on each load)
static AceLmParams         g_lm_params;
static AceSynthParams      g_synth_params;
static AceUnderstandParams g_und_params;

// limits
static int  g_max_batch   = 1;
static int  g_mp3_kbps    = 128;
static bool g_keep_loaded = false;

// job system: all compute endpoints create a job and return its ID
// immediately. the worker thread processes jobs in FIFO order, stores
// the result. the client polls GET /job?id=N until done, then fetches
// the result with GET /job?id=N&result=1.
// cancel: POST /job?id=N&cancel=1 sets the per-job flag.
struct Job {
    std::string       id;
    std::atomic<int>  status{ 0 };  // 0=running 1=done 2=failed 3=cancelled
    std::string       result_body;
    std::string       result_mime;
    std::atomic<bool> cancel{ false };

    // memory ordering contract: result_body and result_mime are written
    // before status is stored (seq_cst). the client loads status (seq_cst)
    // and only reads result fields after seeing done/failed. this guarantees
    // visibility without an explicit mutex on the result fields.
};

static std::mutex                                            mtx_jobs;
static std::unordered_map<std::string, std::shared_ptr<Job>> g_jobs;
static std::deque<std::string>                               g_job_order;
static const int                                             MAX_JOBS = 32;

// generate a random hex ID (64 bits of entropy, non-predictable)
static std::string job_make_id() {
    static std::mt19937_64      rng(std::random_device{}());
    static std::mutex           mtx_rng;
    std::lock_guard<std::mutex> lock(mtx_rng);
    char                        buf[17];
    snprintf(buf, sizeof(buf), "%016llx", (unsigned long long) rng());
    return buf;
}

static std::shared_ptr<Job> job_create() {
    std::lock_guard<std::mutex> lock(mtx_jobs);
    auto                        job = std::make_shared<Job>();
    job->id                         = job_make_id();
    g_jobs[job->id]                 = job;
    g_job_order.push_back(job->id);

    // evict oldest completed jobs to stay under MAX_JOBS.
    // running jobs (status 0) are never evicted.
    while ((int) g_job_order.size() > MAX_JOBS) {
        bool evicted = false;
        for (auto it = g_job_order.begin(); it != g_job_order.end(); ++it) {
            auto jit = g_jobs.find(*it);
            if (jit == g_jobs.end() || jit->second->status.load() != 0) {
                if (jit != g_jobs.end()) {
                    g_jobs.erase(jit);
                }
                g_job_order.erase(it);
                evicted = true;
                break;
            }
        }
        if (!evicted) {
            break;
        }
    }
    return job;
}

static std::shared_ptr<Job> job_find(const std::string & id) {
    std::lock_guard<std::mutex> lock(mtx_jobs);
    auto                        it = g_jobs.find(id);
    return it != g_jobs.end() ? it->second : nullptr;
}

static const char * job_status_str(int s) {
    switch (s) {
        case 0:
            return "running";
        case 1:
            return "done";
        case 2:
            return "failed";
        case 3:
            return "cancelled";
        default:
            return "unknown";
    }
}

// log capture: intercept stderr via pipe, forward to terminal + ring buffer.
// SSE clients connect to /logs and receive lines in real time.
#define LOG_RING_BITS 9
#define LOG_RING_SIZE (1 << LOG_RING_BITS)
#define LOG_RING_MASK (LOG_RING_SIZE - 1)

static std::mutex              mtx_log;
static std::condition_variable cv_log;
static std::string             log_ring[LOG_RING_SIZE];
static uint64_t                log_seq = 0;

static int g_real_stderr_fd = -1;
static int g_pipe_read_fd   = -1;

static void setup_log_capture() {
    g_real_stderr_fd = fd_dup(STDERR_FILENO);
    int pipefd[2];
    if (fd_pipe(pipefd) != 0) {
        g_real_stderr_fd = -1;
        return;
    }
    g_pipe_read_fd = pipefd[0];
    fd_dup2(pipefd[1], STDERR_FILENO);
    fd_close(pipefd[1]);
}

// reader thread: drain pipe, forward to real stderr, push lines to ring.
// exits when the write end of the pipe is closed (fd_dup2 restores real stderr).
static void log_reader_main() {
    char        buf[4096];
    std::string partial;
    for (;;) {
        int n = fd_read(g_pipe_read_fd, buf, sizeof(buf));
        if (n <= 0) {
            break;
        }
        fd_write(g_real_stderr_fd, buf, (size_t) n);
        partial.append(buf, (size_t) n);
        size_t pos;
        while ((pos = partial.find('\n')) != std::string::npos) {
            std::lock_guard<std::mutex> lock(mtx_log);
            log_ring[log_seq & LOG_RING_MASK] = partial.substr(0, pos);
            log_seq++;
            cv_log.notify_all();
            partial.erase(0, pos + 1);
        }
    }
    if (!partial.empty()) {
        std::lock_guard<std::mutex> lock(mtx_log);
        log_ring[log_seq & LOG_RING_MASK] = std::move(partial);
        log_seq++;
        cv_log.notify_all();
    }
    fd_close(g_pipe_read_fd);
}

static void teardown_log_capture() {
    if (g_real_stderr_fd < 0) {
        return;
    }
    fflush(stderr);
    fd_dup2(g_real_stderr_fd, STDERR_FILENO);
    // g_real_stderr_fd stays open: the reader thread writes to it
}

// RAII: captures stderr on construction, restores + joins reader on destruction.
// safe on any exit path (early arg errors, model load failures, normal shutdown).
struct LogCapture {
    std::thread reader;

    LogCapture() {
        setup_log_capture();
        reader = std::thread(log_reader_main);
    }

    ~LogCapture() {
        teardown_log_capture();
        cv_log.notify_all();
        if (reader.joinable()) {
            reader.join();
        }

        // reader is done draining the pipe, safe to close
        if (g_real_stderr_fd >= 0) {
            fd_close(g_real_stderr_fd);
            g_real_stderr_fd = -1;
        }
    }
};

// GET /logs: SSE stream of stderr lines.
// sends backlog (up to LOG_RING_SIZE) then streams new lines in real time.
static void handle_logs(const httplib::Request &, httplib::Response & res) {
    res.set_header("Cache-Control", "no-cache");
    res.set_header("X-Accel-Buffering", "no");
    res.set_chunked_content_provider(
        "text/event-stream", [cursor = uint64_t(0), init = false](size_t, httplib::DataSink & sink) mutable -> bool {
            std::unique_lock<std::mutex> lock(mtx_log);
            if (!init) {
                uint64_t avail = log_seq < LOG_RING_SIZE ? log_seq : (uint64_t) LOG_RING_SIZE;
                cursor         = log_seq - avail;
                while (cursor < log_seq) {
                    std::string ev = "data: " + log_ring[cursor & LOG_RING_MASK] + "\n\n";
                    cursor++;
                    lock.unlock();
                    if (!sink.write(ev.c_str(), ev.size())) {
                        return false;
                    }
                    lock.lock();
                }
                init = true;
            }
            cv_log.wait_for(lock, std::chrono::seconds(2));
            while (cursor < log_seq) {
                std::string ev = "data: " + log_ring[cursor & LOG_RING_MASK] + "\n\n";
                cursor++;
                lock.unlock();
                if (!sink.write(ev.c_str(), ev.size())) {
                    return false;
                }
                lock.lock();
            }
            return true;
        });
}

// cancel callback: checks the per-job cancel flag.
static bool server_cancel_job(void * data) {
    auto * flag = (const std::atomic<bool> *) data;
    return flag && flag->load(std::memory_order_relaxed);
}

// helper: set a JSON error response
static void json_error(httplib::Response & res, int status, const char * msg) {
    yyjson_mut_doc * doc  = yyjson_mut_doc_new(NULL);
    yyjson_mut_val * root = yyjson_mut_obj(doc);
    yyjson_mut_doc_set_root(doc, root);
    yyjson_mut_obj_add_str(doc, root, "error", msg);
    char * json = yyjson_mut_write(doc, 0, NULL);
    yyjson_mut_doc_free(doc);
    res.status = status;
    res.set_content(json, "application/json");
    free(json);
}

// resolve model name: explicit request > already loaded > first in bucket
static std::string resolve_name(const std::vector<ModelEntry> & bucket,
                                const std::string &             requested,
                                const std::string &             loaded) {
    if (!requested.empty()) {
        return requested;
    }
    if (!loaded.empty()) {
        return loaded;
    }
    if (!bucket.empty()) {
        return bucket[0].name;
    }
    return "";
}

// server-side routing fields parsed from JSON (not part of AceRequest)
struct ServerFields {
    std::string        synth_model;
    std::string        lm_model;
    std::string        vae_model;
    std::string        adapter;
    float              adapter_scale;
    AdapterGroupScales adapter_gs;
    std::string        adapter_mode;  // "merge" or "runtime"
};

static void parse_server_fields(const char * json, ServerFields * sf) {
    sf->synth_model   = "";
    sf->lm_model      = "";
    sf->vae_model     = "";
    sf->adapter       = "";
    sf->adapter_scale = 1.0f;
    sf->adapter_mode  = "";

    yyjson_doc * doc = yyjson_read(json, strlen(json), 0);
    if (!doc) {
        return;
    }
    yyjson_val * root = yyjson_doc_get_root(doc);
    if (!root) {
        yyjson_doc_free(doc);
        return;
    }

    // for arrays, take server fields from the first element
    yyjson_val * obj = root;
    if (yyjson_is_arr(root)) {
        obj = yyjson_arr_get_first(root);
    }
    if (!obj || !yyjson_is_obj(obj)) {
        yyjson_doc_free(doc);
        return;
    }

    yyjson_val * v;
    if ((v = yyjson_obj_get(obj, "synth_model")) && yyjson_is_str(v)) {
        sf->synth_model = yyjson_get_str(v);
    }
    if ((v = yyjson_obj_get(obj, "lm_model")) && yyjson_is_str(v)) {
        sf->lm_model = yyjson_get_str(v);
    }
    if ((v = yyjson_obj_get(obj, "vae_model")) && yyjson_is_str(v)) {
        sf->vae_model = yyjson_get_str(v);
    }
    if ((v = yyjson_obj_get(obj, "adapter")) && yyjson_is_str(v)) {
        sf->adapter = yyjson_get_str(v);
    }
    if ((v = yyjson_obj_get(obj, "adapter_scale")) && yyjson_is_num(v)) {
        sf->adapter_scale = (float) yyjson_get_num(v);
    }

    // per-group adapter scales: {"adapter_group_scales": {"self_attn": 1.0, ...}}
    yyjson_val * gs_obj = yyjson_obj_get(obj, "adapter_group_scales");
    if (gs_obj && yyjson_is_obj(gs_obj)) {
        yyjson_val * gs_v;
        if ((gs_v = yyjson_obj_get(gs_obj, "self_attn")) && yyjson_is_num(gs_v)) {
            sf->adapter_gs.self_attn = (float) yyjson_get_num(gs_v);
        }
        if ((gs_v = yyjson_obj_get(gs_obj, "cross_attn")) && yyjson_is_num(gs_v)) {
            sf->adapter_gs.cross_attn = (float) yyjson_get_num(gs_v);
        }
        if ((gs_v = yyjson_obj_get(gs_obj, "mlp")) && yyjson_is_num(gs_v)) {
            sf->adapter_gs.mlp = (float) yyjson_get_num(gs_v);
        }
        if ((gs_v = yyjson_obj_get(gs_obj, "cond_embed")) && yyjson_is_num(gs_v)) {
            sf->adapter_gs.cond_embed = (float) yyjson_get_num(gs_v);
        }
    }
    if ((v = yyjson_obj_get(obj, "adapter_mode")) && yyjson_is_str(v)) {
        sf->adapter_mode = yyjson_get_str(v);
    }

    yyjson_doc_free(doc);
}

// load LM. frees understand (shared pointers become invalid) but does not rebuild it.
// returns false on failure (caller returns 500).
static bool ensure_lm(const std::string & name) {
    if (g_ctx_lm && g_loaded_lm == name) {
        return true;
    }

    const ModelEntry * entry = registry_find(g_registry.lm, name.c_str());
    if (!entry) {
        fprintf(stderr, "[Server] LM not found: %s\n", name.c_str());
        return false;
    }

    // understand holds shared LM pointers, free before LM reload
    ace_understand_free(g_ctx_understand);
    g_ctx_understand = nullptr;
    g_loaded_und_dit.clear();
    ace_lm_free(g_ctx_lm);
    g_ctx_lm = nullptr;

    // load new
    fprintf(stderr, "[Server] Loading LM: %s\n", name.c_str());
    g_lm_params.model_path = entry->path.c_str();
    g_ctx_lm               = ace_lm_load(&g_lm_params);
    if (!g_ctx_lm) {
        fprintf(stderr, "[Server] FATAL: LM load failed\n");
        g_loaded_lm.clear();
        return false;
    }

    g_loaded_lm = name;
    return true;
}

// load understand pipeline (LM + tokenizer from DiT).
// reloads when LM or DiT changes. tokenizer weights differ between DiT variants.
static bool ensure_understand(const std::string & lm_name, const std::string & dit_name) {
    if (!ensure_lm(lm_name)) {
        return false;
    }

    // already loaded with the same DiT tokenizer
    if (g_ctx_understand && g_loaded_und_dit == dit_name) {
        return true;
    }

    // update dit_path for the tokenizer
    const ModelEntry * dit = registry_find(g_registry.dit, dit_name.c_str());
    if (dit) {
        g_und_params.dit_path = dit->path.c_str();
    }

    // (re)build understand with shared LM
    ace_understand_free(g_ctx_understand);
    g_ctx_understand = nullptr;

    g_und_params.shared_model = ace_lm_get_model(g_ctx_lm);
    g_und_params.shared_bpe   = ace_lm_get_bpe(g_ctx_lm);
    g_ctx_understand          = ace_understand_load(&g_und_params);
    if (!g_ctx_understand) {
        fprintf(stderr, "[Server] FATAL: understand load failed\n");
        g_loaded_und_dit.clear();
        return false;
    }

    g_loaded_und_dit = dit_name;
    return true;
}

// load synth pipeline (DiT + adapter + text-enc + VAE). frees previous context first.
// returns false on failure (caller returns 500).
static bool ensure_synth(const std::string &        dit_name,
                         const std::string &        adapter_name,
                         float                      adapter_scale,
                         const AdapterGroupScales & adapter_gs = {},
                         const std::string &        adapter_mode = "",
                         const std::string &        vae_name = "") {
    // Resolve VAE name for cache comparison
    std::string resolved_vae = resolve_name(g_registry.vae, vae_name, g_loaded_vae);

    // cache key: reload only when model, adapter, overall scale, group scales, OR VAE change
    if (g_ctx_synth && g_loaded_dit == dit_name && g_loaded_adapter == adapter_name &&
        g_loaded_adapter_scale == adapter_scale &&
        g_loaded_adapter_gs.self_attn  == adapter_gs.self_attn &&
        g_loaded_adapter_gs.cross_attn == adapter_gs.cross_attn &&
        g_loaded_adapter_gs.mlp        == adapter_gs.mlp &&
        g_loaded_adapter_gs.cond_embed == adapter_gs.cond_embed &&
        g_loaded_adapter_mode          == adapter_mode &&
        g_loaded_vae                   == resolved_vae) {
        return true;
    }

    // need text-encoder + vae singletons
    if (g_registry.text_enc.empty() || g_registry.vae.empty()) {
        fprintf(stderr, "[Server] Missing Text-Enc or VAE in registry\n");
        return false;
    }

    const ModelEntry * dit = registry_find(g_registry.dit, dit_name.c_str());
    if (!dit) {
        fprintf(stderr, "[Server] DiT not found: %s\n", dit_name.c_str());
        return false;
    }

    // unload old
    ace_synth_free(g_ctx_synth);
    g_ctx_synth = nullptr;

    // set paths
    g_synth_params.text_encoder_path = g_registry.text_enc[0].path.c_str();
    g_synth_params.dit_path          = dit->path.c_str();

    // resolve VAE: use requested name, or fall back to first available
    const ModelEntry * vae_entry = registry_find(g_registry.vae, resolved_vae.c_str());
    if (!vae_entry && !g_registry.vae.empty()) {
        vae_entry = &g_registry.vae[0];
    }
    if (!vae_entry) {
        fprintf(stderr, "[Server] No VAE available\n");
        g_loaded_dit.clear();
        return false;
    }
    g_synth_params.vae_path = vae_entry->path.c_str();
    fprintf(stderr, "[Server] VAE: %s\n", vae_entry->name.c_str());

    // resolve adapter
    if (!adapter_name.empty()) {
        const AdapterEntry * adapter = registry_find_adapter(g_registry, adapter_name.c_str());
        if (!adapter) {
            // Fallback: treat adapter_name as an absolute path if the file exists on disk.
            // This supports the file browser UI which sends full paths for adapters outside
            // the pre-scanned --adapters directory.
            static AdapterEntry dynamic_adapter;
            if (registry_is_file(adapter_name.c_str())) {
                // extract just the filename for the name field
                std::string fname = adapter_name;
                auto sep = fname.find_last_of("/\\");
                if (sep != std::string::npos) {
                    fname = fname.substr(sep + 1);
                }
                dynamic_adapter = { fname, adapter_name };
                adapter = &dynamic_adapter;
                fprintf(stderr, "[Server] Adapter resolved from absolute path: %s\n", adapter_name.c_str());
            }
        }
        if (!adapter) {
            fprintf(stderr, "[Server] Adapter not found: %s\n", adapter_name.c_str());
            g_loaded_dit.clear();
            g_loaded_adapter.clear();
            return false;
        }
        g_synth_params.adapter_path  = adapter->path.c_str();
        g_synth_params.adapter_scale = adapter_scale;
        g_synth_params.adapter_group_self_attn   = adapter_gs.self_attn;
        g_synth_params.adapter_group_cross_attn  = adapter_gs.cross_attn;
        g_synth_params.adapter_group_mlp         = adapter_gs.mlp;
        g_synth_params.adapter_group_cond_embed  = adapter_gs.cond_embed;
        g_synth_params.adapter_mode  = adapter_mode.empty() ? nullptr : adapter_mode.c_str();
    } else {
        g_synth_params.adapter_path  = nullptr;
        g_synth_params.adapter_scale = 1.0f;
        g_synth_params.adapter_group_self_attn   = 1.0f;
        g_synth_params.adapter_group_cross_attn  = 1.0f;
        g_synth_params.adapter_group_mlp         = 1.0f;
        g_synth_params.adapter_group_cond_embed  = 1.0f;
        g_synth_params.adapter_mode  = nullptr;
    }

    fprintf(stderr, "[Server] Loading synth: DiT=%s%s%s\n", dit_name.c_str(),
            adapter_name.empty() ? "" : " Adapter=", adapter_name.c_str());
    g_ctx_synth = ace_synth_load(&g_synth_params);
    if (!g_ctx_synth) {
        fprintf(stderr, "[Server] FATAL: synth load failed\n");
        g_loaded_dit.clear();
        g_loaded_adapter.clear();
        return false;
    }

    g_loaded_dit           = dit_name;
    g_loaded_adapter       = adapter_name;
    g_loaded_adapter_scale = adapter_scale;
    g_loaded_adapter_gs    = adapter_gs;
    g_loaded_adapter_mode  = adapter_mode;
    g_loaded_vae           = vae_entry->name;
    return true;
}

// LM worker: generates metadata + lyrics + codes, stores JSON result in job.
static void lm_worker(std::shared_ptr<Job> job, AceRequest ace_req, ServerFields sf, int lm_batch_size, int mode) {
    if (job->cancel.load()) {
        job->status.store(3);
        return;
    }

    // load
    std::string lm_name = resolve_name(g_registry.lm, sf.lm_model, g_loaded_lm);
    if (!ensure_lm(lm_name)) {
        job->status.store(2);
        return;
    }

    // execute
    std::vector<AceRequest> out(lm_batch_size);
    int rc = ace_lm_generate(g_ctx_lm, &ace_req, lm_batch_size, out.data(), NULL, NULL, server_cancel_job,
                             (void *) &job->cancel, mode);

    // free
    if (!g_keep_loaded) {
        ace_understand_free(g_ctx_understand);
        g_ctx_understand = nullptr;
        ace_lm_free(g_ctx_lm);
        g_ctx_lm = nullptr;
        g_loaded_lm.clear();
        g_loaded_und_dit.clear();
    }

    if (rc != 0) {
        job->status.store(job->cancel.load() ? 3 : 2);
        return;
    }

    // serialize output as a JSON array
    std::string body = "[";
    for (int i = 0; i < lm_batch_size; i++) {
        if (i > 0) {
            body += ",";
        }
        body += request_to_json(&out[i]);
    }
    body += "]";

    job->result_body = std::move(body);
    job->result_mime = "application/json";
    job->status.store(1);
    fprintf(stderr, "[Server] Job %s done (LM, %d results)\n", job->id.c_str(), lm_batch_size);
}

// POST /lm[?mode=inspire|format]
// accepts: AceRequest JSON (+ optional "lm_model" for LM selection)
// returns: JSON {"id":"N"} immediately. result is a JSON array of enriched
// AceRequests (lm_batch_size controls count).
// modes:
//   (none)    full: metadata + lyrics + audio codes
//   inspire   short caption -> metadata + lyrics (no codes)
//   format    caption + lyrics -> metadata + lyrics (no codes)
static void handle_lm(const httplib::Request & req, httplib::Response & res) {
    if (g_registry.lm.empty()) {
        json_error(res, 501, "No LM models in registry");
        return;
    }

    // parse mode from URL parameter
    int mode = LM_MODE_GENERATE;
    if (req.has_param("mode")) {
        std::string m = req.get_param_value("mode");
        if (m == "inspire") {
            mode = LM_MODE_INSPIRE;
        } else if (m == "format") {
            mode = LM_MODE_FORMAT;
        } else {
            json_error(res, 400, "Invalid mode (use: inspire, format)");
            return;
        }
    }

    // parse server fields + request
    ServerFields sf;
    parse_server_fields(req.body.c_str(), &sf);

    AceRequest ace_req;
    if (!request_parse_json(&ace_req, req.body.c_str())) {
        json_error(res, 400, "Invalid JSON");
        return;
    }
    if (ace_req.caption.empty()) {
        json_error(res, 400, "Caption is required");
        return;
    }

    // clamp lm_batch_size to [1, max_batch]
    int lm_batch_size = ace_req.lm_batch_size;
    if (lm_batch_size < 1) {
        lm_batch_size = 1;
    }
    if (lm_batch_size > g_max_batch) {
        lm_batch_size = g_max_batch;
    }

    auto job = job_create();
    fprintf(stderr, "[Server] Job %s created (LM, mode=%d)\n", job->id.c_str(), mode);

    work_push([job, ace_req, sf, lm_batch_size, mode]() { lm_worker(job, ace_req, sf, lm_batch_size, mode); });

    std::string body = "{\"id\":\"" + job->id + "\"}";
    res.set_content(body, "application/json");
}

// synth worker: processes synth request, stores audio result in job.
static void synth_worker(std::shared_ptr<Job>    job,
                         std::vector<AceRequest> ace_reqs,
                         ServerFields            sf,
                         float *                 src_interleaved,
                         int                     src_len,
                         float *                 ref_interleaved,
                         int                     ref_len,
                         bool                    output_wav,
                         WavFormat               wav_fmt,
                         int                     peak_clip,
                         bool                    req_keep_loaded) {
    // One group per original request: same codes = same T per group, so the
    // synth_batch_size copies inside a group stack into a single GPU batch.
    // Different requests can have different T and become separate groups.
    const int batch_n     = (int) ace_reqs.size();
    int       total_alloc = 0;
    for (int ri = 0; ri < batch_n; ri++) {
        int sbs = ace_reqs[ri].synth_batch_size;
        total_alloc += sbs < 1 ? 1 : (sbs > 9 ? 9 : sbs);
    }
    std::vector<AceAudio> audio(total_alloc);

    if (job->cancel.load()) {
        free(src_interleaved);
        free(ref_interleaved);
        job->status.store(3);
        return;
    }

    // Load resident modules (TextEnc, CondEnc, FSQ). DiT and VAE are phased.
    std::string dit_name = resolve_name(g_registry.dit, sf.synth_model, g_loaded_dit);
    std::string vae_name = resolve_name(g_registry.vae, sf.vae_model, g_loaded_vae);
    if (!ensure_synth(dit_name, sf.adapter, sf.adapter_scale, sf.adapter_gs, sf.adapter_mode, vae_name)) {
        free(src_interleaved);
        free(ref_interleaved);
        job->status.store(2);
        return;
    }

    // Build per-request groups with resolved seeds.
    std::vector<std::vector<AceRequest>> groups(batch_n);
    for (int ri = 0; ri < batch_n; ri++) {
        auto & r   = ace_reqs[ri];
        int    sbs = r.synth_batch_size;
        if (sbs < 1) {
            sbs = 1;
        }
        if (sbs > 9) {
            sbs = 9;
        }
        request_resolve_seed(&r);
        const long long base_seed = r.seed;

        groups[ri].resize(sbs);
        for (int i = 0; i < sbs; i++) {
            groups[ri][i]      = r;
            groups[ri][i].seed = base_seed + i;
        }
    }

    // Two-phase run: DiT resident for all groups, optionally co-resident with VAE.
    const bool keep = g_keep_loaded || req_keep_loaded;
    const int rc = synth_batch_run(g_ctx_synth, groups, src_interleaved, src_len, ref_interleaved, ref_len,
                                   audio.data(), keep, server_cancel_job, (void *) &job->cancel);
    if (rc != 0) {
        if (!keep) {
            ace_synth_free(g_ctx_synth);
            g_ctx_synth = nullptr;
            g_loaded_dit.clear();
            g_loaded_adapter.clear();
            g_loaded_vae.clear();
        }
        free(src_interleaved);
        free(ref_interleaved);
        for (auto & a : audio) {
            ace_audio_free(&a);
        }
        job->status.store(job->cancel.load() ? 3 : 2);
        return;
    }

    // Drop the pipeline unless --keep-loaded or per-request keep_loaded asks to keep it.
    if (!keep) {
        ace_synth_free(g_ctx_synth);
        g_ctx_synth = nullptr;
        g_loaded_dit.clear();
        g_loaded_adapter.clear();
        g_loaded_vae.clear();
    }
    free(src_interleaved);
    free(ref_interleaved);
    const int total_tracks = total_alloc;

    // encode each track (peak normalize + encode)
    const char * mime = output_wav ? "audio/wav" : "audio/mpeg";

    std::vector<std::string> encoded(total_tracks);
    for (int b = 0; b < total_tracks; b++) {
        if (!audio[b].samples) {
            continue;
        }
        if (!output_wav || wav_fmt != WAV_F32) {
            audio_normalize(audio[b].samples, audio[b].n_samples * 2, peak_clip);
        }
        if (output_wav) {
            encoded[b] = audio_encode_wav(audio[b].samples, audio[b].n_samples, 48000, wav_fmt);
        } else {
            encoded[b] = audio_encode_mp3(audio[b].samples, audio[b].n_samples, 48000, g_mp3_kbps, server_cancel_job,
                                          (void *) &job->cancel);
        }
        ace_audio_free(&audio[b]);
    }

    // store result in job
    // single track: raw audio body
    if (total_tracks == 1) {
        job->result_body = std::move(encoded[0]);
        job->result_mime = mime;
    } else {
        // multiple tracks: multipart/mixed, each part is raw audio
        std::string boundary = "ace-batch-boundary";
        std::string body;
        for (int b = 0; b < total_tracks; b++) {
            body += "--" + boundary + "\r\n";
            body += "Content-Type: ";
            body += mime;
            body += "\r\n\r\n";
            body += encoded[b];
            body += "\r\n";
        }
        body += "--" + boundary + "--\r\n";
        job->result_body = std::move(body);
        job->result_mime = "multipart/mixed; boundary=" + boundary;
    }

    job->status.store(job->cancel.load() ? 3 : 1);
    fprintf(stderr, "[Server] Job %s done (%d tracks)\n", job->id.c_str(), total_tracks);
}

// POST /synth[?format=wav16|wav24|wav32]
// returns JSON {"id":"N"} immediately.
// input:
//   application/json body        -> single request {} or batch [{req0}, {req1}, ...]
//   multipart/form-data          -> single request + audio file(s)
//     part "request":   JSON text
//     part "audio":     source audio (WAV or MP3)
//     part "ref_audio": timbre reference audio (WAV or MP3), optional
// output: audio/mpeg (default) or audio/wav (?format=wav16|wav24|wav32)
//   batch == 1: raw audio body
//   batch >  1: multipart/mixed, each part is raw audio
// Batch size = number of JSON objects (after synth_batch_size expansion, clamped to 9).
// Metadata (seed, duration, etc) is already in the request JSON from /lm.
static void handle_synth(const httplib::Request & req, httplib::Response & res) {
    if (g_registry.dit.empty() || g_registry.text_enc.empty() || g_registry.vae.empty()) {
        json_error(res, 501, "No synth models in registry (need dit + text-encoder + vae)");
        return;
    }

    // parse server fields from JSON body (before multipart parsing)
    ServerFields sf;

    // parse request: plain JSON (single or array) or multipart (JSON + audio file)
    std::vector<AceRequest> ace_reqs;
    float *                 src_interleaved = nullptr;
    int                     src_len         = 0;
    float *                 ref_interleaved = nullptr;
    int                     ref_len         = 0;

    if (req.is_multipart_form_data()) {
        // multipart mode: single request + optional audio files
        AceRequest ace_req;

        std::string json_body;
        if (req.form.has_file("request")) {
            json_body = req.form.get_file("request").content;
        } else if (req.form.has_field("request")) {
            json_body = req.form.get_field("request");
        } else {
            json_error(res, 400, "Multipart: missing 'request' part");
            return;
        }
        parse_server_fields(json_body.c_str(), &sf);
        if (!request_parse_json(&ace_req, json_body.c_str())) {
            json_error(res, 400, "Multipart: invalid JSON in 'request' part");
            return;
        }

        if (req.form.has_file("audio")) {
            auto file = req.form.get_file("audio");
            if (file.content.empty()) {
                json_error(res, 400, "Multipart: empty 'audio' part");
                return;
            }
            int     T_audio = 0;
            float * planar  = audio_read_48k_buf((const uint8_t *) file.content.data(), file.content.size(), &T_audio);
            if (!planar || T_audio <= 0) {
                json_error(res, 400, "Failed to decode audio");
                return;
            }
            fprintf(stderr, "[Server] Source audio: %.2fs @ 48kHz\n", (float) T_audio / 48000.0f);
            src_interleaved = audio_planar_to_interleaved(planar, T_audio);
            free(planar);
            src_len = T_audio;
        }

        if (req.form.has_file("ref_audio")) {
            auto file = req.form.get_file("ref_audio");
            if (!file.content.empty()) {
                int     T_audio = 0;
                float * planar =
                    audio_read_48k_buf((const uint8_t *) file.content.data(), file.content.size(), &T_audio);
                if (planar && T_audio > 0) {
                    fprintf(stderr, "[Server] Reference audio: %.2fs @ 48kHz\n", (float) T_audio / 48000.0f);
                    ref_interleaved = audio_planar_to_interleaved(planar, T_audio);
                    free(planar);
                    ref_len = T_audio;
                } else {
                    fprintf(stderr, "[Server] WARNING: failed to decode ref_audio, ignoring\n");
                }
            }
        }
        ace_reqs.push_back(ace_req);
    } else {
        // plain JSON body: single object {} or array [{}, ...]
        parse_server_fields(req.body.c_str(), &sf);
        if (!request_parse_json_array(req.body.c_str(), &ace_reqs)) {
            json_error(res, 400, "Invalid JSON");
            return;
        }
    }

    if (ace_reqs.empty()) {
        json_error(res, 400, "Empty request");
        return;
    }
    if (ace_reqs[0].caption.empty() && ace_reqs[0].task_type != TASK_LEGO && ace_reqs[0].task_type != TASK_EXTRACT &&
        ace_reqs[0].task_type != TASK_COMPLETE) {
        json_error(res, 400, "Caption is required");
        return;
    }

    // output format: ?format=wav16|wav24|wav32 for WAV, default MP3
    bool      output_wav = false;
    WavFormat wav_fmt    = WAV_S16;
    if (req.has_param("format")) {
        bool is_mp3 = true;
        if (audio_parse_format(req.get_param_value("format").c_str(), is_mp3, wav_fmt)) {
            output_wav = !is_mp3;
        }
    }
    int peak_clip = ace_reqs[0].peak_clip;

    // per-request co-resident mode: ?keep_loaded=1
    const bool req_keep_loaded = req.has_param("keep_loaded") && req.get_param_value("keep_loaded") == "1";

    // create job, spawn worker, return ID
    auto job = job_create();
    fprintf(stderr, "[Server] Job %s created (%d requests)\n", job->id.c_str(), (int) ace_reqs.size());

    work_push([job, reqs = std::move(ace_reqs), sf, src_interleaved, src_len, ref_interleaved, ref_len, output_wav,
               wav_fmt, peak_clip, req_keep_loaded]() mutable {
        synth_worker(job, std::move(reqs), sf, src_interleaved, src_len, ref_interleaved, ref_len, output_wav, wav_fmt,
                     peak_clip, req_keep_loaded);
    });

    // return job ID immediately
    std::string body = "{\"id\":\"" + job->id + "\"}";
    res.set_content(body, "application/json");
}

// understand worker: load LM + tokenizer, run understand, store JSON result in job.
static void understand_worker(std::shared_ptr<Job> job,
                              AceRequest           ace_req,
                              ServerFields         sf,
                              float *              src_interleaved,
                              int                  src_len) {
    if (job->cancel.load()) {
        free(src_interleaved);
        job->status.store(3);
        return;
    }

    // load (LM + tokenizer from selected DiT)
    std::string lm_name  = resolve_name(g_registry.lm, sf.lm_model, g_loaded_lm);
    std::string dit_name = resolve_name(g_registry.dit, sf.synth_model, g_loaded_dit);
    if (!ensure_understand(lm_name, dit_name)) {
        free(src_interleaved);
        job->status.store(2);
        return;
    }

    AceRequest out;
    int rc = ace_understand_generate(g_ctx_understand, src_interleaved, src_len, &ace_req, &out, server_cancel_job,
                                     (void *) &job->cancel);

    // free
    if (!g_keep_loaded) {
        ace_understand_free(g_ctx_understand);
        g_ctx_understand = nullptr;
        ace_lm_free(g_ctx_lm);
        g_ctx_lm = nullptr;
        g_loaded_lm.clear();
        g_loaded_und_dit.clear();
    }
    free(src_interleaved);

    if (rc != 0) {
        job->status.store(job->cancel.load() ? 3 : 2);
        return;
    }

    job->result_body = "[" + request_to_json(&out) + "]";
    job->result_mime = "application/json";
    job->status.store(1);
    fprintf(stderr, "[Server] Job %s done (understand)\n", job->id.c_str());
}

// POST /understand
// Two modes:
//   multipart/form-data          -> full pipeline (audio + optional JSON params)
//     part "audio":   WAV or MP3 file (required)
//     part "request": JSON text (optional, for sampling params)
//   application/json body        -> codes-only (audio_codes in JSON, skip VAE+FSQ)
// returns: JSON {"id":"N"} immediately.
static void handle_understand(const httplib::Request & req, httplib::Response & res) {
    if (g_registry.lm.empty() || g_registry.dit.empty() || g_registry.vae.empty()) {
        json_error(res, 501, "Understand requires LM, DiT and VAE models");
        return;
    }

    // parse request: multipart (audio + optional JSON) or plain JSON (codes-only)
    AceRequest ace_req;
    request_init(&ace_req);
    ace_req.lm_temperature = 0.3f;  // understand default: lower than generation
    ace_req.lm_top_p       = 1.0f;  // understand default: no nucleus sampling

    // parse server fields + request
    ServerFields sf;
    float *      src_interleaved = nullptr;
    int          src_len         = 0;

    if (req.is_multipart_form_data()) {
        // multipart: required "audio" part, optional "request" part for sampling params
        if (req.form.has_file("request")) {
            const std::string & json = req.form.get_file("request").content;
            parse_server_fields(json.c_str(), &sf);
            if (!request_parse_json(&ace_req, json.c_str())) {
                json_error(res, 400, "Multipart: invalid JSON in 'request' part");
                return;
            }
        } else if (req.form.has_field("request")) {
            const std::string & json = req.form.get_field("request");
            parse_server_fields(json.c_str(), &sf);
            if (!request_parse_json(&ace_req, json.c_str())) {
                json_error(res, 400, "Multipart: invalid JSON in 'request' part");
                return;
            }
        }

        if (!req.form.has_file("audio")) {
            json_error(res, 400, "Multipart: missing 'audio' part");
            return;
        }
        auto file = req.form.get_file("audio");
        if (file.content.empty()) {
            json_error(res, 400, "Multipart: empty 'audio' part");
            return;
        }

        // decode directly from multipart buffer (WAV/MP3 auto-detected)
        int     T_audio = 0;
        float * planar  = audio_read_48k_buf((const uint8_t *) file.content.data(), file.content.size(), &T_audio);
        if (!planar || T_audio <= 0) {
            json_error(res, 400, "Failed to decode audio");
            return;
        }

        fprintf(stderr, "[Server] Understand source: %.2fs @ 48kHz\n", (float) T_audio / 48000.0f);

        // convert planar [L:T][R:T] to interleaved [L0,R0,L1,R1,...] for pipeline
        src_interleaved = audio_planar_to_interleaved(planar, T_audio);
        free(planar);
        src_len = T_audio;
    } else {
        // plain JSON body: codes-only mode
        parse_server_fields(req.body.c_str(), &sf);
        if (!request_parse_json(&ace_req, req.body.c_str())) {
            json_error(res, 400, "Invalid JSON");
            return;
        }
    }

    auto job = job_create();
    fprintf(stderr, "[Server] Job %s created (understand)\n", job->id.c_str());

    work_push([job, ace_req, sf, src_interleaved, src_len]() {
        understand_worker(job, ace_req, sf, src_interleaved, src_len);
    });

    std::string body = "{\"id\":\"" + job->id + "\"}";
    res.set_content(body, "application/json");
}

// GET /props
// server configuration, available models, and default request.
// the webui reads this at boot to populate dropdowns and status indicators.
static void handle_props(const httplib::Request &, httplib::Response & res) {
    yyjson_mut_doc * doc  = yyjson_mut_doc_new(NULL);
    yyjson_mut_val * root = yyjson_mut_obj(doc);
    yyjson_mut_doc_set_root(doc, root);

    yyjson_mut_obj_add_str(doc, root, "version", ACE_VERSION);

    // helper: build a JSON array of model entry names
    auto add_names = [&](yyjson_mut_val * parent, const char * key, const std::vector<ModelEntry> & bucket) {
        yyjson_mut_val * arr = yyjson_mut_arr(doc);
        for (const auto & e : bucket) {
            yyjson_mut_arr_add_str(doc, arr, e.name.c_str());
        }
        yyjson_mut_obj_add_val(doc, parent, key, arr);
    };

    // models: available model names per bucket
    yyjson_mut_val * models = yyjson_mut_obj(doc);
    yyjson_mut_obj_add_val(doc, root, "models", models);
    add_names(models, "lm", g_registry.lm);
    add_names(models, "embedding", g_registry.text_enc);
    add_names(models, "dit", g_registry.dit);
    add_names(models, "vae", g_registry.vae);

    // adapters: available adapter names
    yyjson_mut_val * adapters_arr = yyjson_mut_arr(doc);
    for (const auto & e : g_registry.adapters) {
        yyjson_mut_arr_add_str(doc, adapters_arr, e.name.c_str());
    }
    yyjson_mut_obj_add_val(doc, root, "adapters", adapters_arr);

    // cli: server settings
    yyjson_mut_val * cli = yyjson_mut_obj(doc);
    yyjson_mut_obj_add_val(doc, root, "cli", cli);
    yyjson_mut_obj_add_int(doc, cli, "max_batch", g_max_batch);
    yyjson_mut_obj_add_int(doc, cli, "mp3_bitrate", g_mp3_kbps);

    // default: full AceRequest with all defaults from request_init().
    // the webui reads this to populate LM placeholders.
    // DiT fields (inference_steps, guidance_scale, shift) are 0 = auto-detect;
    // their resolved placeholders come from presets below.
    AceRequest defaults;
    request_init(&defaults);
    std::string      defaults_str  = request_to_json(&defaults, false);
    yyjson_doc *     defaults_doc  = yyjson_read(defaults_str.c_str(), defaults_str.size(), 0);
    yyjson_mut_val * defaults_copy = yyjson_val_mut_copy(doc, yyjson_doc_get_root(defaults_doc));
    yyjson_mut_obj_add_val(doc, root, "default", defaults_copy);
    yyjson_doc_free(defaults_doc);

    // presets: auto-detect values for DiT sampling params.
    // the webui switches placeholders based on the selected DiT model.
    yyjson_mut_val * presets = yyjson_mut_obj(doc);
    yyjson_mut_obj_add_val(doc, root, "presets", presets);

    yyjson_mut_val * turbo = yyjson_mut_obj(doc);
    yyjson_mut_obj_add_int(doc, turbo, "inference_steps", 8);
    yyjson_mut_obj_add_real(doc, turbo, "guidance_scale", 1.0);
    yyjson_mut_obj_add_real(doc, turbo, "shift", 3.0);
    yyjson_mut_obj_add_val(doc, presets, "turbo", turbo);

    yyjson_mut_val * sft = yyjson_mut_obj(doc);
    yyjson_mut_obj_add_int(doc, sft, "inference_steps", 50);
    yyjson_mut_obj_add_real(doc, sft, "guidance_scale", 1.0);
    yyjson_mut_obj_add_real(doc, sft, "shift", 1.0);
    yyjson_mut_obj_add_val(doc, presets, "sft", sft);

    // serialize
    yyjson_write_flag flags = YYJSON_WRITE_PRETTY | YYJSON_WRITE_PRETTY_TWO_SPACES | YYJSON_WRITE_FP_TO_FIXED(2);
    char *            json  = yyjson_mut_write(doc, flags, NULL);
    yyjson_mut_doc_free(doc);
    res.set_content(json, "application/json");
    free(json);
}

static void usage(const char * prog) {
    fprintf(stderr, "acestep.cpp %s\n\n", ACE_VERSION);
    fprintf(stderr,
            "Usage: %s --models <dir> [options]\n"
            "\n"
            "Required:\n"
            "  --models <dir>          Directory of GGUF model files\n"
            "\n"
            "Adapter:\n"
            "  --adapters <dir>        Directory of adapters\n"
            "\n"
            "Memory control:\n"
            "  --keep-loaded           Keep models in VRAM between requests\n"
            "  --vae-chunk <N>         Latent frames per tile (default: 256)\n"
            "  --vae-overlap <N>       Overlap frames per side (default: 64)\n"
            "\n"
            "Output:\n"
            "  --mp3-bitrate <kbps>    MP3 bitrate (default: 128)\n"
            "\n"
            "Server:\n"
            "  --host <addr>           Listen address (default: 127.0.0.1)\n"
            "  --port <N>              Listen port (default: 8080)\n"
            "  --max-batch <N>         LM batch limit (default: 1)\n"
            "  --max-seq <N>           KV cache size (default: 8192)\n"
            "\n"
            "Debug:\n"
            "  --no-fsm                Disable FSM constrained decoding\n"
            "  --no-fa                 Disable flash attention\n"
            "  --no-batch-cfg          Split CFG into two separate forwards (LM + DiT)\n"
            "  --clamp-fp16            Clamp hidden states to FP16 range\n",
            prog);
}

int main(int argc, char ** argv) {
    ace_lm_default_params(&g_lm_params);
    ace_synth_default_params(&g_synth_params);

    const char * host         = "127.0.0.1";
    int          port         = 8080;
    const char * models_dir   = nullptr;
    const char * adapters_dir = nullptr;

    if (argc < 2) {
        usage(argv[0]);
        return 1;
    }

    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "--models") && i + 1 < argc) {
            models_dir = argv[++i];
        } else if (!strcmp(argv[i], "--adapters") && i + 1 < argc) {
            adapters_dir = argv[++i];
        } else if (!strcmp(argv[i], "--max-seq") && i + 1 < argc) {
            g_lm_params.max_seq = atoi(argv[++i]);

            // vae tiling
        } else if (!strcmp(argv[i], "--vae-chunk") && i + 1 < argc) {
            g_synth_params.vae_chunk = atoi(argv[++i]);
        } else if (!strcmp(argv[i], "--vae-overlap") && i + 1 < argc) {
            g_synth_params.vae_overlap = atoi(argv[++i]);
        } else if (!strcmp(argv[i], "--keep-loaded")) {
            g_keep_loaded = true;

            // output
        } else if (!strcmp(argv[i], "--mp3-bitrate") && i + 1 < argc) {
            g_mp3_kbps = atoi(argv[++i]);

            // server
        } else if (!strcmp(argv[i], "--host") && i + 1 < argc) {
            host = argv[++i];
        } else if (!strcmp(argv[i], "--port") && i + 1 < argc) {
            port = atoi(argv[++i]);
        } else if (!strcmp(argv[i], "--max-batch") && i + 1 < argc) {
            g_max_batch = atoi(argv[++i]);

            // debug
        } else if (!strcmp(argv[i], "--no-fsm")) {
            g_lm_params.use_fsm = false;
        } else if (!strcmp(argv[i], "--no-fa")) {
            g_lm_params.use_fa    = false;
            g_synth_params.use_fa = false;
        } else if (!strcmp(argv[i], "--no-batch-cfg")) {
            g_lm_params.use_batch_cfg    = false;
            g_synth_params.use_batch_cfg = false;
        } else if (!strcmp(argv[i], "--clamp-fp16")) {
            g_lm_params.clamp_fp16    = true;
            g_synth_params.clamp_fp16 = true;

        } else if (!strcmp(argv[i], "--help") || !strcmp(argv[i], "-h")) {
            usage(argv[0]);
            return 0;
        } else {
            fprintf(stderr, "Unknown option: %s\n", argv[i]);
            usage(argv[0]);
            return 1;
        }
    }

    // --models is required
    if (!models_dir) {
        fprintf(stderr, "[Server] ERROR: --models is required\n");
        usage(argv[0]);
        return 1;
    }

    // stderr capture for SSE /logs (must be after arg parsing so --help prints directly)
    LogCapture log_capture;

    // scan models directory (reads GGUF metadata only)
    fprintf(stderr, "[Server] Scanning models in %s\n", models_dir);
    if (!registry_scan(&g_registry, models_dir)) {
        fprintf(stderr, "[Server] ERROR: no GGUF models found in %s\n", models_dir);
        return 1;
    }

    // scan adapters directory (optional)
    if (adapters_dir) {
        fprintf(stderr, "[Server] Scanning adapters in %s\n", adapters_dir);
        registry_scan_adapters(&g_registry, adapters_dir);
    }

    // validate pipeline
    bool have_lm    = !g_registry.lm.empty();
    bool have_dit   = !g_registry.dit.empty();
    bool have_enc   = !g_registry.text_enc.empty();
    bool have_vae   = !g_registry.vae.empty();
    bool have_synth = have_dit && have_enc && have_vae;

    // partial synth: some components found but pipeline incomplete
    if (!have_synth && (have_dit || have_enc || have_vae)) {
        char missing[64];
        int  n = 0;
        if (!have_dit) {
            n += snprintf(missing + n, sizeof(missing) - n, "%sDiT", n ? ", " : "");
        }
        if (!have_enc) {
            n += snprintf(missing + n, sizeof(missing) - n, "%sText-Enc", n ? ", " : "");
        }
        if (!have_vae) {
            n += snprintf(missing + n, sizeof(missing) - n, "%sVAE", n ? ", " : "");
        }
        if (have_lm) {
            fprintf(stderr, "[Server] WARNING: /synth unavailable, missing: %s\n", missing);
        } else {
            fprintf(stderr, "[Server] ERROR: no usable pipeline, synth missing: %s\n", missing);
            return 1;
        }
    }

    // clamp max_batch
    if (g_max_batch < 1) {
        g_max_batch = 1;
    }
    if (g_max_batch > 9) {
        g_max_batch = 9;
    }
    g_lm_params.max_batch = g_max_batch;

    // init understand params (vae for audio encoding, dit resolved per-request)
    ace_understand_default_params(&g_und_params);
    g_und_params.use_fa  = g_lm_params.use_fa;
    g_und_params.use_fsm = g_lm_params.use_fsm;
    if (have_vae) {
        g_und_params.vae_path = g_registry.vae[0].path.c_str();
    }

    bool have_understand = have_lm && have_dit && have_vae;

    // setup HTTP server
    httplib::Server svr;
    g_svr = &svr;

    // per-operation socket idle timeout (httplib default is 5s).
    // generous margin for slow networks and large audio transfers.
    svr.set_read_timeout(600);
    svr.set_write_timeout(600);

    // SO_REUSEADDR: allow rebind after TIME_WAIT (normal restart).
    // no SO_REUSEPORT: fail if another process is actively listening.
    svr.set_socket_options([](socket_t sock) {
        int one = 1;
#ifdef _WIN32
        setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, (const char *) &one, sizeof(one));
#else
        setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &one, sizeof(one));
#endif
    });

    // reject oversized bodies (256 MB: src + ref audio, up to 10min WAV each)
    svr.set_payload_max_length(256 * 1024 * 1024);

    // all endpoints are always registered. handlers return 501 when the
    // backing pipeline has no models in the registry.
    svr.Post("/lm", handle_lm);
    svr.Post("/synth", handle_synth);
    svr.Post("/understand", handle_understand);
    svr.Get("/health", [](const httplib::Request &, httplib::Response & res) {
        res.set_content("{\"status\":\"ok\"}", "application/json");
    });
    svr.Get("/props", handle_props);
    svr.Get("/logs", handle_logs);

    // GET /vram: return GPU memory usage (CUDA only)
    svr.Get("/vram", [](const httplib::Request &, httplib::Response & res) {
#ifdef GGML_USE_CUDA
        size_t free_bytes = 0, total_bytes = 0;
        cudaError_t err = cudaMemGetInfo(&free_bytes, &total_bytes);
        if (err != cudaSuccess) {
            json_error(res, 500, cudaGetErrorString(err));
            return;
        }
        size_t used_bytes = total_bytes - free_bytes;
        char buf[256];
        snprintf(buf, sizeof(buf),
                 "{\"used_mb\":%.0f,\"total_mb\":%.0f,\"free_mb\":%.0f}",
                 (double) used_bytes / (1024.0 * 1024.0),
                 (double) total_bytes / (1024.0 * 1024.0),
                 (double) free_bytes / (1024.0 * 1024.0));
        res.set_content(buf, "application/json");
#else
        res.set_content("{\"used_mb\":0,\"total_mb\":0,\"free_mb\":0}", "application/json");
#endif
    });

    // job system endpoints
    svr.Get("/job", [](const httplib::Request & req, httplib::Response & res) {
        if (!req.has_param("id")) {
            json_error(res, 400, "Missing id parameter");
            return;
        }
        auto job = job_find(req.get_param_value("id"));
        if (!job) {
            json_error(res, 404, "Job not found");
            return;
        }
        // ?result=1: return result body
        if (req.has_param("result") && req.get_param_value("result") == "1") {
            if (job->status.load() != 1) {
                json_error(res, 404, "Result not ready");
                return;
            }
            res.set_content(job->result_body, job->result_mime);
            return;
        }
        // default: return status JSON
        std::string body = "{\"status\":\"";
        body += job_status_str(job->status.load());
        body += "\"}";
        res.set_content(body, "application/json");
    });
    svr.Post("/job", [](const httplib::Request & req, httplib::Response & res) {
        if (!req.has_param("id")) {
            json_error(res, 400, "Missing id parameter");
            return;
        }
        auto job = job_find(req.get_param_value("id"));
        if (!job) {
            json_error(res, 404, "Job not found");
            return;
        }
        // ?cancel=1: cancel the job
        if (req.has_param("cancel") && req.get_param_value("cancel") == "1") {
            job->cancel.store(true);
            fprintf(stderr, "[Server] Cancel requested for job %s\n", job->id.c_str());
            res.set_content("{\"status\":\"cancelled\"}", "application/json");
            return;
        }
        json_error(res, 400, "Unknown action");
    });

    // embedded webui: gzipped single-page app (built by tools/webui/).
    // the browser decompresses transparently via Content-Encoding: gzip.
    // the .gz is committed to git so cloning + cmake + make gives a working UI.
    if (index_html_gz_len > 0) {
        svr.Get("/", [](const httplib::Request & req, httplib::Response & res) {
            if (req.get_header_value("Accept-Encoding").find("gzip") == std::string::npos) {
                res.set_content("Error: gzip is not supported by this browser", "text/plain");
            } else {
                res.set_header("Content-Encoding", "gzip");
                res.set_content(reinterpret_cast<const char *>(index_html_gz), index_html_gz_len,
                                "text/html; charset=utf-8");
            }
        });
    }

    // graceful shutdown on SIGINT/SIGTERM
    signal(SIGINT, on_signal);
    signal(SIGTERM, on_signal);

    // start FIFO worker thread (processes all GPU jobs in order)
    std::thread worker(worker_main);

    fprintf(stderr, "[Server] acestep.cpp %s\n", ACE_VERSION);
    fprintf(stderr, "[Server] Listening on %s:%d\n", host, port);
    fprintf(stderr, "[Server] Pipelines:%s%s%s\n", have_lm ? " /lm" : "", have_synth ? " /synth" : "",
            have_understand ? " /understand" : "");
    fprintf(stderr, "[Server] Models: %zu LM, %zu Text-Enc, %zu DiT, %zu VAE, %zu Adapter\n", g_registry.lm.size(),
            g_registry.text_enc.size(), g_registry.dit.size(), g_registry.vae.size(), g_registry.adapters.size());
    if (!svr.listen(host, port)) {
        fprintf(stderr, "[Server] FATAL: cannot bind %s:%d\n", host, port);
    }

    // stop worker thread (finishes current job, discards pending)
    {
        std::lock_guard<std::mutex> lock(mtx_work);
        g_work_stop = true;
    }
    cv_work.notify_one();
    worker.join();

    // cleanup (all _free functions handle NULL)
    fprintf(stderr, "[Server] Shutting down...\n");
    ace_understand_free(g_ctx_understand);
    ace_synth_free(g_ctx_synth);
    ace_lm_free(g_ctx_lm);
    fprintf(stderr, "[Server] Done\n");

    return 0;
}
