// trainSchemas.ts — zod schemas for the train_prepare / train_start bodies,
// one per route. Each field is one the route (server/src/routes/training.ts)
// reads by name; each "default" is what that route resolves an ABSENT field
// to, read from the handler itself, not from the Options interfaces in
// server/src/services/training/types.ts, whose comments have drifted (e.g.
// PreprocessOptions says maxDuration 240, the route uses 600).
//
// Objects are .strict(): an unknown key is a validation error before any HTTP
// call, never silently dropped. Anything the schema does not name goes
// through the tool's `options` passthrough instead.
//
// ponytail: client-side mirror of the route handlers' defaults. Update the
// descriptions when a route's fallback changes.

import { z } from 'zod';

const n = z.number();
const int = z.number().int();
const bool = z.boolean();
const str = z.string();

// ── train_prepare ───────────────────────────────────────────────────────────

/** POST /datasets/:id/preprocess (training.ts:1757). Needs a built dataset. */
export const acePreprocessSchema = z.object({
  ditModel: str.optional().describe('DiT base the tensors (and so every adapter trained from them) are bound to. Default: the DiT selected in the Models tab (PUT /api/training/active-models), else the first BF16 DiT. 400 if unknown or none installed.'),
  vaeModel: str.optional().describe('Default: first BF16 VAE, else the first VAE.'),
  textEncoder: str.optional().describe('Default: first text encoder.'),
  sampleIds: z.array(str).optional().describe('Default: every non-excluded sample whose file exists.'),
  maxDuration: n.optional().describe('Seconds per song. Default 600; 0 = no truncation; < 0 is a 400.'),
  normalize: z.enum(['peak', 'none']).optional().describe("Default 'peak'."),
  targetDb: n.optional().describe('Default -1.0; -60..0.'),
  dtype: z.enum(['f32', 'bf16']).optional().describe("Default 'f32'."),
  compat: z.enum(['hotstep', 'sidestep']).optional().describe("Default 'hotstep'."),
  maxCaptionTokens: n.optional().describe('Default 512; 16..4096.'),
  maxLyricTokens: n.optional().describe('Default 2048; 16..4096.'),
  vaeChunk: n.optional().describe('Latent frames. Default 384; >= 64.'),
  vaeOverlap: n.optional().describe('Latent frames. Default 48; >= 0 and < vaeChunk.'),
  overwrite: bool.optional().describe('Default false.'),
  stopEngine: bool.optional().describe('Stop ace-server for the job. Default true.'),
  outputDir: str.optional().describe("Default <tensors>/<slug>/<variantKey>. Must be a subdirectory of the dataset's tensors root (400 otherwise)."),
}).strict();

/** POST /datasets/:id/mm3-codes (training.ts:2146). Needs a built dataset. */
export const mm3CodesSchema = z.object({
  maxDuration: n.optional().describe('Seconds per song. Default: no cap (anything not > 0 also means no cap).'),
  launder: bool.optional().describe('Default false. true writes the SEPARATE laundered cache (mm3-codes-laundered/) via ace-train mm3-launder; train with launder: true to use it.'),
}).strict();

/** POST /datasets/:id/yue2-preprocess (training.ts:3184). Out-of-range
 *  numbers fall back to the default SILENTLY (the route's num() helper). */
export const yue2PreprocessSchema = z.object({
  vaeVariant: z.enum(['standard', 'legacy']).optional().describe("Default 'standard'."),
  captionMode: z.enum(['ace', 'yue2', 'txt', 'default', 'none']).optional().describe("Default 'yue2' when the source folder has sidecars with a caption or lyrics, else 'none'. 'default' needs defaultCaption; 'txt' needs acknowledgeSidecarFormat (400 otherwise)."),
  defaultCaption: str.optional().describe("The caption for every clip under captionMode 'default'. Default ''."),
  acknowledgeSidecarFormat: bool.optional().describe("Required true for captionMode 'txt': that mode feeds the whole ACE .txt sidecar in as the style prompt."),
  decode: z.enum(['auto', 'ffmpeg']).optional().describe("Default 'auto'. 'ffmpeg' is a 400 without an ffmpeg binary."),
  loudnessLufs: n.optional().describe("Default: absent = the engine's -14 LUFS. 0 = off; else -40..0 (400 outside). Part of the cache key: a change re-encodes."),
  clipSeconds: n.optional().describe('Default 10; 1..60.'),
  tileFrames: n.optional().describe('Default 750; 1..100000.'),
  haloFrames: n.optional().describe('Default 20; 12..4096.'),
  only: str.optional().describe("Default '' (all files)."),
  limit: n.optional().describe('Default 0 (no limit); 0..100000.'),
  force: bool.optional().describe('Default false.'),
}).strict();

/** POST /datasets/:id/yue2-joint-prepare (training.ts:3960). CPU job. */
export const yue2JointPrepareSchema = z.object({
  models: z.object({ vae: str, semantic: str, sheetsage: str }).strict().optional()
    .describe('Model file paths. Default: resolved from the YuE2 latent manifest and the installed models (see train_runs readiness.jointPrepare.defaults). The route also takes a repeatable `model` ["vae=FILE", ...] form; send that through options.'),
  legacyManifest: str.optional().describe("The YuE2 latent manifest from the preprocess stage. Default: this dataset's own; any other dataset's is a 400. The route also accepts it as `manifest`."),
  checkpoint: str.optional().describe('Recorded as provenance only. Default: the ConvRot checkpoint if installed, else the LM GGUF.'),
  tokenizer: str.optional().describe('Default: the YuE2 LM GGUF (it carries the text vocabulary).'),
  output: str.optional().describe('Default: a fresh aitk-prepared-<timestamp> dir beside the latent manifest. Must not exist yet.'),
  lyricTiming: bool.optional().describe('Default true.'),
}).strict();

// ── train_start ─────────────────────────────────────────────────────────────

/** POST /datasets/:id/train-lm (training.ts:5108). */
export const aceLmSchema = z.object({
  variantKey: str.optional().describe('Preprocess variant to train from. Default: the newest. Unknown is a 400.'),
  lmSize: z.enum(['0.6B', '1.7B', '4B']).optional().describe("Default '4B'."),
  lmModel: str.optional().describe('LM GGUF. Default: the BF16 model matching lmSize. Unknown is a 400.'),
  ditModel: str.optional().describe("DiT whose FSQ tokenizer extracts the codes. Default: the variant's own DiT."),
  adapterName: str.optional().describe('Default: the dataset slug. [A-Za-z0-9._-]{1,64}.'),
  epochs: n.optional().describe('Hard cap per leg. Default 150; 1..200.'),
  targetLoss: n.optional().describe('Final target. Default 4.0; 0..20; 0 = no auto-stop.'),
  targetLossStages: z.array(n).optional().describe('Explicit target chain, strictly descending (0 only last), one ace-train leg each. Default: the 2.0 and 1.5 rungs above targetLoss, then targetLoss — so [4.0], one leg, at the default targetLoss.'),
  initAdapter: str.optional().describe("Resume source: a run dir or 'latest'. Default: scratch when the chain has more than one leg; with ONE leg (the default chain) 'latest' — the newest non-calibrated run of this adapter name, or scratch if none. '' counts as absent (training.ts:5592), so it does NOT force scratch on a one-leg chain: use a new adapterName or a multi-leg targetLossStages. A resume collapses the chain to [targetLoss] unless targetLossStages is sent."),
  adapterType: z.enum(['lora', 'lokr']).optional().describe("Default 'lora'. On any resume (including the default 'latest' one) adapterType, rank, alpha, the lokr* fields, weights and pissa/hotPizza are ignored: the engine adopts them from the source run."),
  rank: n.optional().describe('Default 16; 1..256.'),
  alpha: n.optional().describe('Default 32; 1..1024.'),
  lokrDim: n.optional().describe('Default 128; 4..4096 (lokr only).'),
  lokrAlpha: n.optional().describe('Default 128.'),
  lokrFactor: n.optional().describe('Default 6; -1 or 2..64 (lokr only).'),
  lokrDecomposeBoth: bool.optional().describe('Default true.'),
  optimizer: z.enum(['adamw', 'muon', 'prodigy']).optional().describe("Default 'adamw' (the route's resolution; types.ts's 'prodigy' comment is stale)."),
  muonLrScale: n.optional().describe('Default 20; 0.001..1000.'),
  muonNsSteps: n.optional().describe('Default 5; 1..20.'),
  learningRate: n.optional().describe('Default 0.0001; > 0 and <= 1.'),
  gradAccum: n.optional().describe('Default 2; 1..64.'),
  gradClip: n.optional().describe('Default 1.0; 0..100; 0 disables.'),
  warmupRatio: n.optional().describe('Default 0.05; 0..0.5.'),
  weightDecay: n.optional().describe('Default 0.01; 0..1.'),
  maxLen: n.optional().describe('Default 0 = auto-fit from free VRAM; else 512..16384.'),
  seed: n.optional().describe('Default 42.'),
  milestoneStep: n.optional().describe('Default 0 = milestones off; 0..5.'),
  milestoneKeep: n.optional().describe('Default 6; 0..64.'),
  lowVram: z.enum(['auto', 'on', 'off']).optional().describe("Default 'auto'."),
  attnHeadBlock: n.optional().describe('Default 0 = engine picks; 0..128. > 0 with a flash attnBackend is a 400.'),
  chunk: n.optional().describe('Default 0 = engine default (128); else 16..1024.'),
  attnBackend: z.enum(['exact', 'flash', 'flash-f32']).optional().describe("Default 'flash'. Coerced to 'exact' when the artist token is on and prefixN > 0, which is the default (token on → prefixN 8)."),
  weights: z.enum(['f32-window', 'bf16']).optional().describe("Default 'bf16'. bf16 + bwd 'mm' is a 400."),
  bwd: z.enum(['outprod', 'mm']).optional().describe("Default 'outprod'."),
  batch: z.union([n, z.literal('auto')]).optional().describe('Must be 1 (the default); anything else is a 400 — micro-batching is not built.'),
  captionDropout: n.optional().describe('Default 0.3; 0..1. Needs a trigger word (the variant\'s custom_tag): the default silently drops to 0 without one, an explicit value is a 400.'),
  regEvery: n.optional().describe('Prior-preservation cadence. Default 0 = off; >= 2 when on. An explicit value with no other 600 s corpus available is a 400.'),
  regTopk: n.optional().describe('Default 64; 1..256.'),
  regSongs: n.optional().describe('Default 24; 1..200.'),
  regTeacher: z.enum(['cached', 'live']).optional().describe("Default 'cached'."),
  regCorpora: z.union([z.literal('auto'), z.array(str)]).optional().describe("Default 'auto' (up to 6 other artists preprocessed at 600 s). An array must be existing lm_codes.jsonl paths under data/training/tensors/."),
  calibrate: bool.optional().describe('Run post-training calibration. Default false.'),
  calibrateRepoint: bool.optional().describe('Default true.'),
  stages: z.array(z.enum(['extract', 'train', 'export'])).optional().describe('Default all three.'),
  artistToken: str.optional().describe("Learned artist token. Default ON, named after the adapter; '' switches it off."),
  artistTokenK: n.optional().describe('Default 32; clamped to 1..256.'),
  artistTokenLr: n.optional().describe('Default 0.005; clamped to 0..1.'),
  prefixN: n.optional().describe('KV prefix columns. Default 8 when the artist token is on, else 0; clamped to 0..64.'),
  lossOnCot: bool.optional().describe('Default true.'),
  order: z.enum(['shuffle', 'fixed']).optional().describe("Default 'shuffle'."),
  overwrite: bool.optional().describe('Re-extract every song. Default false.'),
  stopEngine: bool.optional().describe('Default true.'),
  rslora: bool.optional().describe('Default false.'),
  dora: bool.optional().describe('Default false. The LoRA-family methods resolve silently by precedence dora > hira > loha > pissa > hra; rslora combines with any of the first four, and hra + rslora is a 400. All are LoRA-only and dropped silently under lokr.'),
  hira: bool.optional().describe('Default false.'),
  loha: bool.optional().describe('Default false.'),
  pissa: bool.optional().describe('Default false.'),
  hotPizza: bool.optional().describe('Default false. Implies pissa.'),
  hra: bool.optional().describe('Default false.'),
  loraPlusRatio: n.optional().describe('Default 1 (off).'),
}).strict();

/** POST /datasets/:id/train-dit (training.ts:5794). The base DiT is never
 *  taken from the request: it is the variant's own. */
export const aceDitSchema = z.object({
  variantKey: str.optional().describe('Preprocess variant to train from. Default: the newest. Unknown is a 400.'),
  adapterName: str.optional().describe('Default: the dataset slug. [A-Za-z0-9._-]{1,64}.'),
  adapterType: z.enum(['lora', 'lokr']).optional().describe("Default 'lokr'. Changes the defaults of learningRate, weightDecay and lossWeighting. On a resume (the default whenever a previous run exists) the engine adopts the adapter shape (type, rank, alpha, lokr*, layers, targetMlp, pissa) from the source run, but those three defaults still follow THIS field."),
  initAdapter: str.optional().describe("Resume source: a run dir or 'latest'. Default 'latest' — the newest non-calibrated run of this adapter name, or scratch if none. '' forces scratch."),
  epochs: n.optional().describe('Hard cap. Default 500; 1..2000.'),
  targetLoss: n.optional().describe('Default 0.3; 0..20; 0 = no auto-stop.'),
  rank: n.optional().describe('Default 128; 1..256. Used by lora, but range-checked (400) for either type, as are the lokr* fields.'),
  alpha: n.optional().describe('Default 256; 1..1024.'),
  lokrDim: n.optional().describe('Default 512; 4..4096.'),
  lokrAlpha: n.optional().describe('Default 512; 0..8192; 0 = dim.'),
  lokrFactor: n.optional().describe('Default 6; -1 or 2..64.'),
  lokrDecomposeBoth: bool.optional().describe('Default true.'),
  targetMlp: bool.optional().describe('Default true.'),
  dora: bool.optional().describe('Default false. hra + rslora is a 400.'),
  hira: bool.optional().describe('Default false.'),
  loha: bool.optional().describe('Default false.'),
  pissa: bool.optional().describe('Default false.'),
  hra: bool.optional().describe('Default false.'),
  rslora: bool.optional().describe('Default false.'),
  loraPlusRatio: n.optional().describe('Default 1 (off).'),
  layers: n.optional().describe('Default 0 = auto; 0..64.'),
  crop: n.optional().describe('Default 0 = auto-fit; else 128..8192 frames.'),
  cropMin: n.optional().describe('Default 375; 128..8192.'),
  cropMax: n.optional().describe('Default 0 = engine default cap; else 128..8192 and >= cropMin.'),
  cropAnchor: z.enum(['song', 'zero']).optional().describe("Default 'song'."),
  cropMode: z.enum(['structured', 'random']).optional().describe("Default 'structured'."),
  cropStartFrac: n.optional().describe('Default 0.2; with cropEndFrac >= 0 and summing to <= 1.'),
  cropEndFrac: n.optional().describe('Default 0.2.'),
  cropJitter: bool.optional().describe('Default false.'),
  learningRate: n.optional().describe('Default 0.002 (lokr) / 0.0005 (lora); > 0 and <= 1.'),
  gradAccum: n.optional().describe('Default 4; 1..64.'),
  gradClip: n.optional().describe('Default 1.0; 0..100.'),
  warmupRatio: n.optional().describe('Default 0.05; 0..0.5.'),
  weightDecay: n.optional().describe('Default 0.001 (lokr) / 0.01 (lora); 0..1.'),
  lossWeighting: z.enum(['none', 'flow_snr']).optional().describe("Default 'none' (lokr) / 'flow_snr' (lora)."),
  snrGamma: n.optional().describe('Default 5; 1..100.'),
  tBias: n.optional().describe('Default 0.5; 0..4.'),
  channelBalance: bool.optional().describe('Default true.'),
  timestepMu: n.optional().describe('Default -0.4; -4..4.'),
  timestepSigma: n.optional().describe('Default 1.0; > 0 and <= 4.'),
  tMin: n.optional().describe('Default 0; 0..1, < tMax.'),
  tMax: n.optional().describe('Default 1; 0..1.'),
  cfgRatio: n.optional().describe('Default 0.15; 0..1.'),
  genreRatio: n.optional().describe('Percent. Default 30; 0..100.'),
  seed: n.optional().describe('Default 42.'),
  order: z.enum(['shuffle', 'fixed']).optional().describe("Default 'shuffle'."),
  milestoneStep: n.optional().describe('Default 0.1; 0..5; 0 disables.'),
  milestoneKeep: n.optional().describe('Default 6; 0..64.'),
  vramReserveMb: n.optional().describe('Default 2048; 0..16384.'),
  batch: n.optional().describe('Default 1; 1..16.'),
  ckptSegments: n.optional().describe('Default 1 (auto); 0 = off; 2..32 fixed.'),
  optimizer: z.enum(['adamw', 'muon', 'prodigy']).optional().describe("Default 'prodigy'."),
  muonLrScale: n.optional().describe('Default 20; 0.001..1000.'),
  muonMomentum: n.optional().describe('Default 0.95; 0..0.999.'),
  muonNsSteps: n.optional().describe('Default 5; 1..20.'),
  muonMinDim: n.optional().describe('Default 16; 1..4096.'),
  mirror: z.enum(['f32', 'bf16', 'bf16-f32']).optional().describe("Default 'bf16-f32'."),
  bwd: z.enum(['outprod', 'mm']).optional().describe("Default 'mm'."),
  attnBackend: z.enum(['exact', 'flash', 'flash-f32']).optional().describe("Default 'exact'."),
  stages: z.array(z.enum(['train', 'export'])).optional().describe('Default both.'),
  overwrite: bool.optional().describe('Default false.'),
  stopEngine: bool.optional().describe('Default true.'),
  calibrate: bool.optional().describe('Default false.'),
  calibrateRepoint: bool.optional().describe('Default true.'),
}).strict();

/** POST /datasets/:id/mm3-train-lm (training.ts:2342). Absent fields take
 *  MM3_LM_DEFAULTS (services/training/mm3Train.ts:513), with the named preset
 *  laid over it. Out-of-range numbers fall back to the default SILENTLY. */
export const mm3LmSchema = z.object({
  preset: z.enum(['fast', 'balanced', 'thorough']).optional().describe('Sits under the explicit fields. fast/balanced/thorough = 300/600/900 steps (lr 8e-5, maxFrames 9000, prefixFrames 0, prefixChunk 256). Absent: the plain defaults, 500 steps.'),
  basePrecision: str.optional().describe("An installed base id (train_runs readiness.mm3.bases). Default 'q8_0'; an id that is not installed also falls back to 'q8_0'."),
  launder: bool.optional().describe('Train on the laundered codes cache. Default false. 400 if that cache is empty.'),
  rank: n.optional().describe('Default 128; 1..512.'),
  alpha: n.optional().describe('Default 128; 1..2048.'),
  lr: n.optional().describe('Default 8e-5; 1e-7..1e-2.'),
  steps: n.optional().describe('Default 500 (or the preset\'s); 1..100000. The cap in both stop modes.'),
  saveEvery: n.optional().describe('Default 100; 0..100000.'),
  warmup: n.optional().describe('Default 25; 0..100000.'),
  gradAccum: n.optional().describe('Default 1; 1..64.'),
  seed: n.optional().describe('Default 42.'),
  maxFrames: n.optional().describe('Default 9000; 64..9000.'),
  longTracks: z.enum(['exclude', 'crop', 'excise']).optional().describe("Default 'exclude'. 400 if exclude would drop more than half the tracks."),
  cropMode: z.enum(['random', 'beginning', 'structured']).optional().describe("Default 'structured'."),
  cropStartFrac: n.optional().describe('Default 0.2; 0..1.'),
  cropEndFrac: n.optional().describe('Default 0.15; 0..1.'),
  cropStartTiles: n.optional().describe('Default 1; 1..64.'),
  cropAnchor: z.enum(['song', 'zero']).optional().describe("Default 'song'."),
  endCropVary: bool.optional().describe('Default false.'),
  endCropMin: n.optional().describe('Default 128; 1..9000.'),
  regScoreLast: n.optional().describe('Default 0; 0..9000.'),
  scoreLast: n.optional().describe('Default 0; 0..9000.'),
  scoreLastEndOnly: bool.optional().describe('Default false.'),
  keepResumeState: bool.optional().describe('Default false.'),
  verifyExport: bool.optional().describe('Default false.'),
  lyricsDropout: n.optional().describe('Default 0; 0..1.'),
  trimTrailingSilence: bool.optional().describe('Default false.'),
  depthLossWeight: n.optional().describe('Default 1.0; 0..10.'),
  depthLossFrames: n.optional().describe('Default 128; 1..1024.'),
  optimizer: z.enum(['muon', 'adamw', 'prodigy']).optional().describe("Default 'adamw'."),
  muonLrScale: n.optional().describe('Default 64; 0.01..4096.'),
  holdout: n.optional().describe('Default 0.15; 0..0.5.'),
  evalEvery: n.optional().describe('Default 250; 0..100000.'),
  evalCrop: n.optional().describe('Default 750; 8..9000, clamped to maxFrames.'),
  rankDropout: n.optional().describe('Default 0.1; 0..0.9.'),
  adapterType: z.enum(['lora', 'lokr']).optional().describe("Default 'lora'."),
  lokrFactor: n.optional().describe('Default 6; 1..64.'),
  lokrDim: n.optional().describe('Default 512; 1..8192.'),
  lokrAlpha: n.optional().describe('Default 512; 1..8192.'),
  attnBackend: z.enum(['exact', 'flash']).optional().describe("Default 'flash'. Coerced to 'exact' on an engine with no fused attention-training kernel (Vulkan, Metal); the response echoes the value used."),
  rslora: bool.optional().describe('Default false.'),
  dora: bool.optional().describe('Default false. More than one of dora/hira/loha/pissa/hra sent as true, or any of them with lokr, is a 400.'),
  hira: bool.optional().describe('Default false.'),
  loha: bool.optional().describe('Default false.'),
  pissa: bool.optional().describe('Default true (ignored under lokr). pissa: false (with hotPizza absent) also turns HOT-PiZZA off.'),
  hotPizza: bool.optional().describe('Default true. Implies pissa.'),
  pissaCache: bool.optional().describe('Default true.'),
  pissaFrozenF16: bool.optional().describe('Default true.'),
  hra: bool.optional().describe('Default false. hra + rslora is a 400. hra: true ALONE is dropped silently and the run trains HOT-PiZZA, because pissa defaults on and wins (mm3Train.ts:1333): send pissa: false with it. dora/hira/loha alone are fine.'),
  loraPlusRatio: n.optional().describe('Default 1; 1..64.'),
  artistToken: str.optional().describe("Default '' (off)."),
  artistTokenK: n.optional().describe('Default 32; 1..256.'),
  artistTokenLr: n.optional().describe('Default 0.005; 1e-6..1.'),
  prefixN: n.optional().describe('Default 0; 0..64. With a regularisation corpus it is a 400.'),
  prefixFrames: n.optional().describe('Default 0 (off); 0..9000.'),
  prefixChunk: n.optional().describe('Default 256; 32..2048.'),
  prefixSelftest: bool.optional().describe('Default true.'),
  trigger: str.optional().describe("Default: the dataset's custom tag."),
  triggerPrepend: bool.optional().describe('Default true.'),
  lrEndFrac: n.optional().describe('Default 0.005; 0..1.'),
  stopMode: z.enum(['steps', 'loss']).optional().describe("Default 'steps'."),
  targetLoss: n.optional().describe('Default 1.0; 0..100. Used when stopMode is loss.'),
  targetLossMetric: z.enum(['train', 'eval']).optional().describe("Default 'train'. 'eval' with stopMode loss needs holdout > 0 and evalEvery > 0 (400 otherwise)."),
  targetLossEpochs: n.optional().describe('Default 5; 1..10000.'),
  regularisation: z.object({
    datasetId: str.optional().describe('Another dataset with RVQ codes (train_runs readiness.mm3.regCandidates). Not this one.'),
    corpusDir: str.optional().describe('A folder with dataset.json, captions and codes/*.codes. Takes precedence over datasetId.'),
    every: n.optional().describe('Default 3; <= 0 = off; 1 is a 400.'),
    topK: n.optional().describe('Default 64; clamped to 1..256.'),
  }).strict().optional().describe('Prior preservation. Default off.'),
  preview: z.object({
    everySteps: n.optional().describe('Default 0; 0..100000.'),
    everyMinutes: n.optional().describe('Default 0; 0..1440. Both cadences 0 = previews off.'),
    seconds: n.optional().describe('Default 40; 8..120.'),
    seed: n.optional().describe('Default 424242.'),
    caption: str.optional(),
    lyrics: str.optional(),
    previewSongId: str.optional(),
    control: bool.optional().describe('Default true.'),
    controlCaption: str.optional(),
    baseline: bool.optional().describe('Default true.'),
    scaleMlp: n.optional().describe('0..2. Default: the planner\'s.'),
    scaleAttn: n.optional().describe('0..2. Default: the planner\'s.'),
  }).strict().optional().describe('Mid-run previews. Default off.'),
}).strict();

const yue2JointPreview = z.object({
  enabled: bool.optional().describe('Default false.'),
  everySteps: int.optional().describe('Default saveEvery; 0..100000.'),
  seconds: int.optional().describe('Default 90; 8..360.'),
  takes: int.optional().describe('Default 1; 1..4.'),
  odeSteps: int.optional().describe('Default 0 (engine default); 0..64.'),
  narCacheRatio: n.optional().describe('0..0.9.'),
  seed: int.optional().describe('Default 424242.'),
  previewMaxFrames: int.optional().describe('Default 2250; 0..9000.'),
  baseline: bool.optional().describe('Default false.'),
  control: bool.optional().describe('Default false.'),
  parallel: bool.optional().describe('Default false.'),
  sharedSheet: bool.optional().describe('Default false.'),
  caption: str.optional(),
  lyrics: str.optional(),
  lyricsSource: z.literal('dataset').optional(),
  previewSongId: str.optional(),
}).strict();

/** POST /datasets/:id/yue2-joint-train (training.ts:3428). trainingMethod is
 *  NOT a field here: the tool sets it to 'aitk' itself and rejects any
 *  caller attempt to set it. Absent advanced knobs mean the ENGINE default
 *  (the route forwards nothing). */
export const yue2JointSchema = z.object({
  steps: int.describe('Total steps. Required (400 without it). On a resume it must exceed resumeStep.'),
  saveEvery: int.optional().describe('Checkpoint cadence, 1..steps. Required on a fresh run (400 without it); on a resume it is inherited from the run, except that refine may set it and refinePlanner forces it to steps.'),
  resumeRunId: str.optional().describe('Resume a run listed by train_runs (yue2-joint). Must be sent with resumeStep. Base, seed, optimizer, adapter shape, dataset, lyricTiming and cursorWeight come from that run; only the stop target, preview and refine fields can change. A base-matched run re-applies its recipe on resume, which clears refine/refinePlanner/freezePlannerNow and the loss/KL targets (read from the code, not exercised).'),
  resumeStep: int.optional().describe('Checkpoint step of resumeRunId that has an optimizer state. Must be sent with resumeRunId.'),
  autoPrepare: bool.optional().describe('Default false. true (fresh runs only) makes the job run joint preparation first with the readiness defaults, so `dataset` is not needed. Without it a fresh run needs `dataset`. A resume never auto-prepares.'),
  preparation: z.object({
    models: z.object({ vae: str, semantic: str, sheetsage: str }).strict().optional(),
    legacyManifest: str.optional(),
    tokenizer: str.optional(),
  }).strict().optional().describe('Overrides for autoPrepare. Ignored without it.'),
  dataset: str.optional().describe('Prepared dataset.json (the `manifest` a train_prepare yue2 joint-prepare run returns). Required unless autoPrepare.'),
  base: str.optional().describe('Base id (train_runs readiness.jointPrepare.bases). Default: the first runnable base.'),
  checkpoint: str.optional().describe('Explicit base checkpoint file; overrides base.'),
  output: str.optional().describe('Default: a new dir under the adapters root named after the trigger. Must not exist (or be empty with previews on).'),
  resume: str.optional().describe('Low-level: an optimizer checkpoint file. Prefer resumeRunId/resumeStep, which fill this in.'),
  seed: int.optional().describe('Default 42; uint32.'),
  device: str.optional().describe('ggml device, e.g. CUDA0, Vulkan0, MTL0, CPU. Default: from the engine build (CUDA0 on CUDA).'),
  method: z.enum(['tuned', 'base-matched']).optional().describe("Default 'tuned'. 'base-matched' forces: stopMode steps (targetLoss/targetKl/targetKlMode cleared, narExtraSteps 0), lrSchedule cosine-floor with lrFloor 0.1, arTargets base, klWeight 0, captionDropout 0, plannerLrScale 1, narLrScale 1, cursorWeight 0 (lyric timing off whatever lyricTiming says), the spike/recon guards off, planCheck/refine/refinePlanner/freezePlannerNow cleared, autoRefine false. It fills blanks with optimizer adamw-lm, lr 1e-4, weightDecay 0.1, beta1 0.9, beta2 0.95, abcDropout 0.5, narCropFrames 1500, arLossWeight 0.25, gradAccum 4, text/lyric/bothDropout 0.1, warmup 3% of steps. An explicit optimizer 'adamw' with it is a 400 (cosine-floor needs another optimizer)."),
  calibrated: bool.optional().describe('Base-matched fresh runs only: scale steps and saveEvery to the album length. Default false.'),
  optimizer: z.enum(['adamw', 'adamw-lm', 'prodigy', 'muon']).optional().describe("Default 'adamw'."),
  cautious: bool.optional().describe('Default false. Needs an optimizer other than adamw.'),
  rank: int.optional().describe('Default 64; 1..65536.'),
  alpha: n.optional().describe('Default 64; > 0.'),
  prodigyD0: n.optional().describe('> 0. Default: engine.'),
  adapterType: z.enum(['lora', 'lokr']).optional().describe("Default 'lora'."),
  lokrDim: int.optional().describe('1..65536. Default: engine.'),
  lokrFactor: int.optional().describe('1..65536. Default: engine.'),
  muonLrScale: n.optional().describe('> 0. Default: engine.'),
  muonNsSteps: int.optional().describe('1..20. Default: engine.'),
  stopMode: z.enum(['steps', 'loss', 'kl']).optional().describe("Default 'steps'."),
  targetLoss: n.optional().describe('Required (>= 0) when stopMode is loss.'),
  targetKl: n.optional().describe('Required (> 0, <= 100) when stopMode is kl.'),
  targetKlMode: z.enum(['mean', 'trend']).optional().describe("kl only. Default 'mean'."),
  narExtraSteps: int.optional().describe('kl only; >= 0.'),
  lr: n.optional().describe('> 0, <= 1. Default: engine.'),
  weightDecay: n.optional().describe('0..10. Default: engine.'),
  klWeight: n.optional().describe('0..100. Default: engine.'),
  abcDropout: n.optional().describe('0..1. Default: engine.'),
  captionDropout: n.optional().describe('0..1. Default: engine.'),
  plannerLrScale: n.optional().describe('> 0, <= 100. Default: engine.'),
  narLrScale: n.optional().describe('> 0, <= 100. Default: engine.'),
  spikeFactor: n.optional().describe('0..1000. Default: off.'),
  spikeStop: int.optional().describe('0..1000. Default: off.'),
  spikeStopWindow: int.optional().describe('1..100000.'),
  reconStop: n.optional().describe('0..0.999. Default: off.'),
  reconStopWindow: int.optional().describe('1..1000.'),
  reconTarget: n.optional().describe('0..10. Default: none.'),
  reconKeepDelta: n.optional().describe('0..1.'),
  lrSchedule: z.enum(['cosine', 'cosine-floor', 'constant', 'linear', 'wsd', 'sgdr']).optional().describe("Default: the engine's cosine. Anything else needs an optimizer other than adamw."),
  lrDecayShape: z.enum(['linear', 'cosine']).optional(),
  lrFloor: n.optional().describe('0..1.'),
  lrDecaySteps: int.optional().describe('1..100000.'),
  lrCycleSteps: int.optional().describe('1..100000.'),
  lrCycleMult: n.optional().describe('1..10.'),
  lrScale: n.optional().describe('0.001..10.'),
  klOvershootMargin: n.optional().describe('0..10.'),
  narCropFrames: int.optional().describe('0 (whole song) or 1..12288. Default: engine.'),
  arCropFrames: int.optional().describe('1..12288. 0 or absent = whole song.'),
  warmup: int.optional().describe('0..steps (above steps the JOB fails, not the route). Default: engine.'),
  arLossWeight: n.optional().describe('> 0, <= 10.'),
  beta1: n.optional().describe('0..0.999999.'),
  beta2: n.optional().describe('0..0.999999.'),
  gradAccum: int.optional().describe('1..256. Default: engine. Above 1 needs lyric timing off (cursorWeight 0): with the default timing on, the route accepts it and the JOB fails.'),
  textDropout: n.optional().describe('0..1; the three dropouts sum to <= 1. Any of them above 0 needs lyric timing off and captionDropout 0, or the JOB fails (the route accepts it).'),
  lyricDropout: n.optional().describe('0..1.'),
  bothDropout: n.optional().describe('0..1.'),
  arTargets: z.enum(['tuned', 'base']).optional().describe("Default 'tuned'."),
  planCheck: z.object({
    every: int.describe('1..100000.'),
    plans: int.optional().describe('1..64.'),
    margin: n.optional().describe('0..1.'),
    seed: int.optional(),
    caption: str.optional(),
    lyrics: str.optional(),
  }).strict().optional().describe('Plan-check planner stop. Only active with stopMode kl and narExtraSteps > 0 (otherwise dropped silently), and needs stopEngine: false or the JOB fails (the route does not check).'),
  stopEngine: bool.optional().describe('Default true (stop ace-server for the run).'),
  lyricTiming: bool.optional().describe('Default true. Alias: alignmentEnabled (lyricTiming wins).'),
  alignmentEnabled: bool.optional(),
  cursorWeight: n.optional().describe('0..10. Default 0.08 with lyric timing on, else 0.'),
  freezePlannerNow: bool.optional().describe('Resume only: freeze the planner.'),
  refine: bool.optional().describe('Resume only: decoder refinement.'),
  refinePlanner: bool.optional().describe('Resume only: planner refinement to targetKl in KL rungs.'),
  klCheckpointEvery: n.optional().describe('refinePlanner: 0.01..1, default 0.1.'),
  refineLrScale: n.optional().describe('refinePlanner: 0.05..1, default 0.3.'),
  autoRefine: bool.optional().describe('Fresh runs only: chain a planner refinement after the run.'),
  preview: yue2JointPreview.optional().describe('Checkpoint previews. Default off.'),
}).strict();
